### DISCUSSION TITLE
Improving Docker and WSL2 for php applications

### DISCUSSION THREAD

**Discussion by Henroks** [microsoft/WSL#6477] [Q&A]
After reading and searching for the past 3-4 days I understand that due to the slower "communication" between the windows mounted folder to the WSL2 (where the code will be actually executed), languages that aren't compiled or maybe if your application depends on a large number of files, you are probably having a bad time with execution times. 

I have tried multiple ways to improve this, but all have failed so far. Does anyone ever came to a proper solution to this issue?

Here is my example and options that I have tried:
_docker-compose.yml_
```
  ts_php:
    build: ./env/php7.4
    privileged: true
    networks:
      - default
    working_dir: /app
    expose:
      - 9000
    volumes:
      - ./:/app
```

Obviously if I chose to not mount on windows and let the application only exist inside the container it will be super fast, but that closes the door for me to use PHP Storm, which is my IDE of choice.

I explored [this](https://gist.github.com/onomatopellan/90024008a0d8c8a2ed6fa57e8b64df54) and [this](https://devblogs.microsoft.com/commandline/access-linux-filesystems-in-windows-and-wsl-2/) option as well. The idea was to store the application in the WSL2 file system and access it on windows, but I had no success.
Is it possible to do something like this? Have the application stored in the "container" and access it on windows through explorer (without using wsl$//, which doesnt work well with php storm)?
