### DISCUSSION TITLE
WSL2 Docker volumes mounting DRVFS

### DISCUSSION THREAD

**Discussion by james-masson** [microsoft/WSL#6840] [Q&A]
In WSL2, I can successfully mount both local disks and network shares via DVFS, eg.

```
mount -t drvfs //my-nas/share /mnt/share
```

Now I'm trying to get docker to do this for me, with a volume definition.

eg.

```
services:
  my-service:
    volumes:
      - nas-share:/container-path

volumes:
  nas-share:
    driver_opts:
      type: drvfs
      device: "//my-nas/share"
```

The error is always `no such device //my-nas/share` - I've tried lots of combinations of slashes and escaping, and taking a look at the mount options given to a pre-existing DRVFS share - I can't get a combination that works

I'm trying to convert over from using the CIFS driver for this purpose, which is working fine, but requires auth credentials.

Has anybody got an example of a DRVFS volume mount working via Docker?
