### DISCUSSION TITLE
Possible to use Windows interop inside Docker containers?

### DISCUSSION THREAD

**Discussion by lizalc** [microsoft/WSL#7370] [Q&A] [answered]
Using Docker for Windows with the WSL2 backend would it be possible to enable Windows interop inside of containers? I'm more curious than anything.

**Comment by Kanti** [comment, marked as answer]
This worked for me:
````yaml
services:
  myservice:
    image: ubuntu
    volumes:
      - .:${PWD}
      - /mnt/:/mnt/
      - /run/WSL:/run/WSL
      - /init:/init:ro
      - /usr/bin/wslpath:/usr/bin/wslpath:ro
    working_dir: ${PWD}
    privileged: true
    init: true
    user: 1000:1000
    environment:
      PATH: $PATH
      WSL2_GUI_APPS_ENABLED: $WSL2_GUI_APPS_ENABLED
      WSL_INTEROP: $WSL_INTEROP
      PULSE_SERVER: $PULSE_SERVER
      WSLENV: $WSLENV
      WSL_DISTRO_NAME: $WSL_DISTRO_NAME
      WT_PROFILE_ID: $WT_PROFILE_ID
      WT_SESSION: $WT_SESSION

````
````bash
# run it like this:
docker compose run myservice explorer.exe .
docker compose run myservice notepad.exe testfile.txt
docker compose run myservice code .
docker compose run myservice phpstorm .
````
