### DISCUSSION TITLE
Docker compose volumes not working

### DISCUSSION THREAD

**Discussion by Depechie** [microsoft/WSL#9021] [Q&A]
I just got a new laptop and wanted to migrate my docker setup from my old laptop.
But somehow the way I previously worked is not functioning with the this fresh install.

So what is working today on my old laptop is the following workflow:

I create docker-compose files and when I need volumes I use following syntax ( example here is with the blackbox image )

```
  blackbox:
    image: prom/blackbox-exporter:v0.22.0
    container_name: blackbox
    restart: unless-stopped
    ports:
      - 9115:9115
    volumes:
      - /var/lib/docker/volumes/otel/blackbox.yml:/etc/blackbox/blackbox.yml
    command: --config.file=/etc/blackbox/blackbox.yml
```

For this to work I need to create an `otel` folder and place the blackbox.yml file in it, all from following windows directory
```
\\wsl$\docker-desktop-data\data\docker\volumes
```
So the compose syntax `/var/lib/docker/volumes/otel` will be mapped to `\\wsl$\docker-desktop-data\data\docker\volumes\otel`

But on the new laptop with same Ubuntu and docker desktop setup, the mapping is not working. As soon as I try out the docker-compose, Ubuntu will actually create a folder inside /var/lib/ instead of using the virtual docker-desktop-data mapping.

What am I'm missing here?
Or do I still need to do some extra configuration?
