### ISSUE TITLE
wsl2 Ubuntu-22.04 The netplan does not work after the restart

### ISSUE THREAD

**Issue by yyyyyyyysssss** [microsoft/WSL#11006]
### Windows Version

Microsoft Windows [版本 10.0.22621.2715]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04

### Other Software

Docker version 23.0.5, build bc4487a

### Repro Steps

wsl --shutdown

### Expected Behavior

netplan config:

```
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: false
      dhcp6: true
      addresses:
        -  172.30.112.2/24
      routes:
      - to: default
        via: 172.30.112.1
      nameservers:
       addresses: [172.30.112.1]
```
run netplan apply is work properly, but netplan does not work after wsl --shutdown is executed

This is the result of executing netplay apply：
![image](https://github.com/microsoft/WSL/assets/105531316/72cae651-81e2-467a-a625-139b546dae99)

This is the result of executing wsl --shutdown：
![image](https://github.com/microsoft/WSL/assets/105531316/8b621c5d-2275-4a75-8258-545c3dfb2af1)

### Actual Behavior

run netplan apply is work properly, but netplan does not work after wsl --shutdown is executed
