### ISSUE TITLE
Kernel 5.15.146.1-2 makes CIFS volumes unstable in Docker Containers (Resource Not Available)

### ISSUE THREAD

**Issue by rg9400** [microsoft/WSL#11227]
### Windows Version

Microsoft Windows [Version 10.0.22631.3155]

### WSL Version

2.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu 22.04

### Other Software

Docker Desktop (Windows) Version 4.27.2

Relevant .wslconfig
```
[wsl2]
memory=48GB
dnsTunneling=false
```

### Repro Steps

1. Create a volume using CIFS for Docker, here is a relevant Compose example
```yaml
volumes:
  drivepool:
    driver_opts:
      type: cifs
      o: username=${HOSTUSER},password=${HOSTPASS},iocharset=utf8,serverino,rw,uid=${PUID},gid=${PGID},file_mode=0777,dir_mode=0777
      device: \\${HOSTIP}\media
```
2. Mount the above volume into a container. Here is an example Compose snippet of how I am mounting it.
```yaml
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - FB_DATABASE=/config/filebrowser.db
      - FB_ADDRESS=0.0.0.0
      - FB_PORT=8080
    volumes:
      - ./filebrowser:/config
      - ~:/srv
      - drivepool:/srv/media
    ports:
      - 8080:8080
    restart: unless-stopped
 ```
3. Go to `localhost:8080` and check how Filebrowser cannot navigate the `media` folder, but it can easily navigate the other folders in `/srv` which were mounted without CIFS. You can run this test with any container of your choice, but you will notice very frequent Resource Not Available errors.
4. Shutdown WSL and switch to the prior kernel release [linux-msft-wsl-5.15.137.3](https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-5.15.137.3)
5. Verify that just by swapping the kernel, everything is resolved, indicating the regression was introduced in 5.15.146

### Expected Behavior

The behavior should be that CIFS is accessible just like any other volume mount without being intermittently disconnected. Basically, the behavior from 5.15.137.3 should carry forward.

### Actual Behavior

It seems like something is causing the containers to break connection with the CIFS mount. It happens very frequently, so the connection seems incredibly unstable.
