### ISSUE TITLE
docker-compose unable to access Hyper-v VM (MobyLinuxVM) filesystem for volume mapping

### ISSUE THREAD

**Issue by jayavigneshksd** [Microsoft/WSL#3062]
When I try to create a compose file containing postgres and provide it with a persistent volume, it fails stating that the mount permission has been denied but when I try to the pass the volume via docker run, it seems to be working fine. 
My login on my Windows machine, is provided by an Active Directory and I am part of the administrators group. I have attached the information below to make reproducing this issue easier.
Also folder under my home directory on Windows seems to be passed in fine. If I pass in a Windows directory, the linux postgres container fails to start.

Windows version: Microsoft Windows [Version 10.0.16299.309]

C:\Users\vdurai\Documents>docker info
```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 8.741GiB
Name: linuxkit-00155d454b01
ID: RWEO:ZDNN:6LWM:LQAL:K33K:26GU:DTYN:6CTU:27UZ:XRU3:N5JF:B5GC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 62
 System Time: 2018-03-28T22:04:56.3589771Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

C:\Users\vdurai\Documents>docker version
```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:06:28 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:14:32 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

C:\Users\vdurai\Documents>docker-compose version
```
docker-compose version 1.20.1, build 5d8c71b2
docker-py version: 3.1.4
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
```
docker-compose.yml
```
version: '2'
services:
  databasePostgres:
     image: postgres:9.2.18
     environment:
       - POSTGRES_PASSWORD=postgres
     volumes:
       - /data_spp/db/postgres:/var/lib/postgresql/data
     ports:
       - "5432:5432"

```
C:\Users\vdurai\Documents>docker-compose config
```
services:
  databasePostgres:
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:9.2.18
    ports:
    - 5432:5432/tcp
    volumes:
    - \data_spp\db\postgres:/var/lib/postgresql/data:rw
version: '2.0'
```

C:\Users\vdurai\Documents>docker-compose up -d
```
Creating spp_databasePostgres_1 ... error

ERROR: for spp_databasePostgres_1  Cannot create container for service databasePostgres: b'Mount denied:\nThe source path "\\\\data_spp\\\\db\\\\postgres:/var/lib/postgresql/data"\nis not a valid Windows path'

ERROR: for databasePostgres  Cannot create container for service databasePostgres: b'Mount denied:\nThe source path "\\\\data_spp\\\\db\\\\postgres:/var/lib/postgresql/data"\nis not a valid Windows path'
ERROR: Encountered errors while bringing up the project.
```

C:\Users\vdurai\Documents>docker run -it -v /data_spp/db/postgres:/var/lib/postgresql/data --rm postgres:9.2.18 bash
root@39cf64b34895:/#
