### ISSUE TITLE
Can't connect to docker swarm container's published port using 'localhost' on windows

### ISSUE THREAD

**Issue by davidwudv** [microsoft/WSL#4729]
* Your Windows build number:  19033.1

* What you're doing and what's happening:  

When I run this command:
```bash
docker run -d -p 80:80 nginx
```
Everythin is ok, I can access the nginx service using `http://localhost:80` on windows browser.

But when I using docker swarm service:
```yaml
version: '3.3'

services:
  nginx:
    image: nginx
    ports:
      - target: 80
        published: 80
        protocol: tcp
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
            condition: on-failure
```

Create docker stack:
```bash
 docker stack deploy --compose-file=nginx.yaml nginx
```

I can't use 'localhost' to access the nginx service on windows.
![image](https://user-images.githubusercontent.com/4150570/70113489-52e60a80-1694-11ea-9c42-ac65635e00f7.png)

But the localhost port is opening:
![image](https://user-images.githubusercontent.com/4150570/70113564-9d678700-1694-11ea-8719-5b548a069083.png)

* What's wrong / what should be happening instead:
 Can't access docker service using 'localhost' on windows.

**Comment by timesnewmen** [comment]
Same issue here.
You could follow this tool to automatically create a host dns record for wsl2 vm. Then use the hostname to access the WSL.
[go-wsl2-host](https://github.com/shayne/go-wsl2-host)

**Comment by wjsgzcn** [comment]
Same issue with exactly the same yml file running with 'docker stack ...'.

'docker-compose up' is ok.

**Comment by wjsgzcn** [comment]
Finally, I find the solution of this problem: in wsl2 terminal, run 'ifconfig' to check your IP address of '**eth0**', in my case the address is '172.22.182.119', visit this address instead of 'localhost', and every thing is ok now. 

Hope Microsoft can resolve this problem, and we can visit localhost instead of the internal address of wsl2.

**Comment by souchprod** [comment]
Hi, is there any progress on this issue ?
 - docker run -p 80:80 nginx 🆗
 - docker-compose up on the below file 🆗
 - docker stack up on the below file ❌

no way to reach the service, even from the wsl2 distro ip

**Comment by davidwudv** [comment]
> Hi, is there any progress on this issue ?
> 
> * docker run -p 80:80 nginx 🆗
> * docker-compose up on the below file 🆗
> * docker stack up on the below file ❌
> 
> no way to reach the service, even from the wsl2 distro ip

@souchprod The problem is still not solved

**Comment by FrankAtHexagon** [comment]
Has this issue been solved? My team is experiencing a similar issue.

**Comment by th0ger** [comment]
Experiencing this still.

**Comment by Winfle** [comment]
Still have the issue

**Comment by viniciusxyz** [comment]
A few months later and I still have the same problem.

**Comment by magnusriga** [comment]
Same here. Does this mean it is currently not possible to use Swarm mode on WSL?

**Comment by omid9h** [comment]
Experiencing this issue too.

**Comment by chanpreetdhanjal** [comment]
Try downloading latest version of WSL following the link below 

https://devblogs.microsoft.com/commandline/windows-subsystem-for-linux-september-2023-update/

**Comment by nmcdtu** [comment]
My colleague found a solution: replacing the ports section in `docker-compose.override.yaml` with the below, then it should work with `localhost:8000` from Windows (provided that the port is 8000)
```yaml
    ports:
        - target: 8080
          published: 8000
          protocol: tcp
          mode: host
```

Tested with Windows 11 10.0.22631.
