### ISSUE TITLE
WSL 2 Linux host cannot be accessed by a custom domain name or 127.0.0.1

### ISSUE THREAD

**Issue by JiXiaoYao** [microsoft/WSL#5728]
# Environment

Windows 10 Professional Insider Preview Build 20180.1000
WSL 2: Ubuntu 20.04 (Linux MSI 4.19.121-microsoft-standard #1 SMP Fri Jun 19 21:06:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux)

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce

I follow this document: https://docs.nvidia.com/cuda/wsl-user-guide/index.html
NVIDIA GPU Docker support installed in WSL 2.
Everything went well, I successfully used RTX 2080 for calculations in WSL 2 Docker.
But when I tried to access the service in Docker on windows, there was a problem.
If I execute curl localhost on the Windows command line, I can access the http (jupyter) service in Docker, but when I customize the domain name in hosts that points to 127.0.0.1, this domain name cannot be used normally when it is accessed Up.

#  Expected behavior
Successfully use my custom domain name to access the docker service

# Actual behavior
The server rejected our connection request.

**Comment by shuohao** [comment]
same

**Comment by EvoSw** [comment]
I think i have the same issue but not with docker

i did upgrade my wsl from 1 to 2 almost allworking smoothly but connection to wsl is not so easy ..

in my ubuntu wsl there is installed apache so when i try to connect i have this beavhior:


http://localhost/   <- WORK
http://127.0.0.1/    <- NOT WORK !!!!!!!!
http://WSL.IPADDRESS   <- WORK

i use tcp dump to check in coming connection and it look like with 127.0.0.1

i try to check if there is other windows app which use port 80 but i got just this

` Get-Process -Id (Get-NetTCPConnection -LocalPort 80).OwningProcess

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    101       8     1012       4692       0,03  11396   1 wslhost`



this is big problem because i have different sites to reach according to domain name.. so on hosts of windows i setup the dns but since i cant use 127.0.0.1 because is not working i need use wsl ipaddress which keep change everytime i restart the machine....

**Comment by Rainbowlemon** [comment]
Having similar issues with OS Build 20185.1000, on WSL2 Ubuntu 18.04.5 LTS (Release 18.04). Trying to access a docker container running in my linux version of docker, and I can access the page using `localhost:port` but can't access it with `dev.project:port`, despite adding the URL to my windows hosts file (and checking the linux hosts file). `127.0.0.1:port` doesn't work either.

**Comment by Nek-** [comment]
As I posted here: https://github.com/microsoft/WSL/issues/4150#issuecomment-674312242

127.0.0.1 does not work but its alter-ego ::1 actually work. You can use [http://[::1]](http://[::1]) !

And you can add custom domain to your hosts:
```
::1 custom.wip
```

**Comment by Rainbowlemon** [comment]
> As I posted here: [#4150 (comment)](https://github.com/microsoft/WSL/issues/4150#issuecomment-674312242)
> 
> 127.0.0.1 does not work but its alter-ego ::1 actually work. You can use [http://[::1]](http://%5B::1%5D) !
> 
> And you can add a custom domain to your hosts:
> 
> ```
> # Instead of `127.0.0.1 custom.wip`
> ::1 custom.wip
> ```

Unfortunately this doesn't work with my current setup (perhaps due to my docker containers)

**Comment by Nek-** [comment]
@Rainbowlemon I'm using it with docker (inside WSL2). I actually use a router on port 80 inside my docker and it works using https://custom.wip. Here is a sample of what I did if it can help:

```yaml
# docker-compose.yaml
services:
  router:
    build: docker/router
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 80:80
      - 443:443
  game:
    image: game-dev:latest
    build:
      target: builder
    volumes:
      - .:/workdir
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.game.rule=Host(`gangbowl.local`)"
      - "traefik.http.routers.game.tls=true"
      - "traefik.http.routers.game-unsecure.rule=Host(`game.local`)"
      # Comment the next line to be able to access frontend via HTTP instead of HTTPS
      - "traefik.http.routers.game-unsecure.middlewares=redirect-to-https@file"
```

I even used mkcert for the certificates and it worked! :)

```makefile
# Makefile
prepare.windows: ## Prepare your system for Gangbowl
	sudo ./build/tools/gang_domain.sh # This setup the hosts!
	./build/tools/mkcert.exe -install
	./build/tools/mkcert.exe -cert-file docker/router/etc/ssl/certs/game.wip.pem -key-file docker/router/etc/ssl/certs/game.wip-key.pem "game.local"
```
