### ISSUE TITLE
Using Docker YML file with context to parent (..) takes too long to build under WSL2

### ISSUE THREAD

**Issue by sdancer75** [microsoft/WSL#6257]
#Environment

```none
Microsoft Windows [Version 10.0.18363.1198]
Your Distribution version: [Release:        20.04]
WSL 2 : [Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020]
```

# Steps to reproduce

I have this folder structure under `/mnt/d/git_projects/`

```
folder_ext
folder_docker
       |---> folder_int
folder_1
folder_2
.......
```
My docker files are all included inside the `folder_docker`. Inside my `docker-compose.yml` file, I set the `context `like this

```
version: '3'
services:
  nginx:
    container_name: my_nginx
    build:
      context: ..
      dockerfile: ./folder_docker/nginx/Dockerfile
```

Inside the `Dockerfile `I copy some files from `folder_ext`

`COPY ./folder_ext /container_folder_ext`

but somewhere below I copy also files from `folder_docker/nginx/nginx.tmp`

`COPY ./folder_docker/nginx/nginx.tmpl /etc/nginx/conf.d/nginx.tmpl`

I am using also `.dockeringore` to ignore folders & files that I am not using.

`docker-compose build`, this takes too long under WSL2 (Ubuntu distro) to begin the building process about ~45 minutes before it starts to process the 1st command inside the Dockerfile.

#  Expected behavior

Running the same script files under Ubuntu it takes no more than 2 seconds to start with the 1st command inside the Dockerfile.

i.e changing the code inside the `docker-compose.yml` file without using the parent directory (..) under the same system using WSL2 it begins in 2 seconds

```
version: '3'
services:
  nginx:
    container_name: my_nginx
    build:
      context: ../folder_ext
      dockerfile: ../folder_docker/nginx/Dockerfile
```

# Actual behavior

No errors actually, but the parent (..) path under context tag, it takes about 45 minutes to begin running the 1st command of the `Dockerfile`. The solution above works but raises other issues ie. _docker forbidden path outside the build context_ and changes have to be made in the `Dockerfile `to make it work.
